# Generated by Django 5.1.5 on 2025-02-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_order_status_order_date_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reference',
            new_name='tx_ref',
        ),
        migrations.AddField(
            model_name='order',
            name='flw_refund_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_refund_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('processed', 'Processed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
