# Generated by Django 5.1.5 on 2025-02-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
