# Generated by Django 5.1.5 on 2025-02-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'paystack'), ('flutterwave', 'flutterwave')], max_length=20),
        ),
    ]
