# Generated by Django 5.1.5 on 2025-03-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('successfull', 'successfull'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('refunded', 'refunded')], default='pending', max_length=20),
        ),
    ]
