# Generated by Django 5.1.5 on 2025-03-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_trackingnumber_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='paystack_refund_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('failed', 'failed'), ('processed', 'processed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
