# Generated by Django 5.1.5 on 2025-03-11 09:46

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paystack_refund_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('failed', 'failed'), ('processed', 'processed')], max_length=20)),
                ('flw_refund_status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='return_image')),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flw_refund_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paystack_refund_status',
        ),
        migrations.AddField(
            model_name='order',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.refund'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.return'),
        ),
    ]
