# Generated by Django 5.1.5 on 2025-03-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_refund_return_remove_order_date_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='return_method',
            field=models.CharField(choices=[('send by yourself', 'send by yourself')], default='send by yourself', max_length=20),
        ),
    ]
