# Generated by Django 5.1.5 on 2025-03-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_returned_return_return_method'),
        ('profiles', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_743fca_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_payment_84a561_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'shipping_status'], name='orders_orde_payment_33bbc7_idx'),
        ),
    ]
