# Generated by Django 5.1.5 on 2025-05-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_orders_orde_created_743fca_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_request',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='returned',
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
