# Generated by Django 5.1.5 on 2025-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_refund_remove_order_return_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost after applying discounts', max_digits=10, null=True),
        ),
    ]
