version: '3.8'

services:
  db:
    image: postgres:17-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  web:
    image: clothing-store-api-dev-web:${IMAGE_TAG}
    build: .
    restart: always
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    env_file:
      - .env
    environment:
      # to override localhost
      - POSTGRES_HOST=db
      - SERVICE_TYPE=web
    depends_on:
      - db
      - redis

  celery:
    image: celery:${IMAGE_TAG}
    build: .
    restart: always
    volumes: 
      - .:/app
      - ./celery/worker:/app/celery/worker
    env_file:
      - .env
    environment:
      # explicitly set it cos dev.py is using localhost
      - CELERY_BROKER_URL=redis://redis:6379/0
      - POSTGRES_HOST=db
      - SERVICE_TYPE=celery
    depends_on:
      - db
      - redis

  celery-beat:
    image: celery-beat:${IMAGE_TAG}
    build: .
    restart: always
    volumes: 
      - .:/app
      - ./celery/beat:/app/celery/beat
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - POSTGRES_HOST=db
      - SERVICE_TYPE=celery-beat
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower:2.0.0
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - FLOWER_BASIC_AUTH=admin:${FLOWER_PASSWORD}
      - BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
  
    