# Generated by Django 5.1.5 on 2025-05-11 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_productdiscount_product'),
        ('shop', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productdiscount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product'),
        ),
    ]
