# Generated by Django 5.1.5 on 2025-05-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_alter_productdiscount_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='used_count',
        ),
    ]
