# Generated by Django 5.1.5 on 2025-05-15 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_alter_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiereddiscount',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('tiered', 'Tiered Discount')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='tiereddiscount',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
