# Generated by Django 5.1.5 on 2025-05-27 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_tiereddiscount_free_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiereddiscount',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
