# Generated by Django 5.1.5 on 2025-06-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_teammember_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='address',
            field=models.CharField(default='Lagos, Nigeria', max_length=500),
        ),
    ]
