version: '3.8'

services:
  db:
    image: postgres:17-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
    

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  web:
    image: clothing-store-api-prod-web:${IMAGE_TAG}
    build:
      context: ../..
      dockerfile: compose/prod/Dockerfile
    command: ["./entrypoint.sh", 
              "gunicorn", "--bind", "0.0.0.0:9000", 
              "clothing_store.wsgi:application"]
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
      - .env.prod.db
    depends_on:
      - db
      - redis

  celery:
    image: celery:${IMAGE_TAG}
    build:
      context: ../..
      dockerfile: compose/prod/Dockerfile
    command: ["../wait-for-it.sh", "celery", "-A", "clothing_store", "worker", "--loglevel=info"]
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  celery-beat:
    image: celery-beat:${IMAGE_TAG}
    build:
      context: ../..
      dockerfile: compose/prod/Dockerfile
    command: ["../wait-for-it.sh", "celery", "-A", "clothing_store", "beat", "--loglevel=info"]
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower:2.0.0
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - .env.prod
    environment:
      - FLOWER_BASIC_AUTH=admin:${FLOWER_PASSWORD}
    depends_on:
      - redis
  
volumes:
  postgres_data: 
  redis_data:
  static_volume: