# Generated by Django 5.1.5 on 2025-02-11 05:11

import apps.common.validators
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.common.validators.validate_file_size], verbose_name='review_image'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[apps.common.validators.validate_file_size], verbose_name='image'),
        ),
    ]
