# Generated by Django 5.1.5 on 2025-02-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review_image_review_product_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_received',
        ),
    ]
