# Generated by Django 5.1.5 on 2025-02-20 22:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_review_product_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='review_image'),
        ),
    ]
