# Generated by Django 5.1.5 on 2025-06-03 17:23

import apps.common.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_discounted_price_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.common.validators.validate_file_size], verbose_name='review_image'),
        ),
    ]
