# Generated by Django 5.1.5 on 2025-02-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupondiscount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdiscount',
            name='discount',
        ),
        migrations.DeleteModel(
            name='CategoryDiscount',
        ),
        migrations.DeleteModel(
            name='CartDiscount',
        ),
    ]
