# Generated by Django 5.1.5 on 2025-02-11 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupondiscount', '0002_remove_cartdiscount_discount_delete_categorydiscount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(unique=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupondiscount.discount')),
            ],
        ),
    ]
