# Generated by Django 5.1.5 on 2025-02-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupondiscount', '0003_orderdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit',
        ),
    ]
