# Generated by Django 5.1.5 on 2025-02-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupondiscount', '0004_remove_coupon_expires_at_remove_coupon_usage_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='firstpurchasediscount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='tiereddiscount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discountassignment',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderdiscount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discountassignment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discountassignment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='firstpurchasediscount',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='TieredDiscount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='OrderDiscount',
        ),
        migrations.DeleteModel(
            name='DiscountAssignment',
        ),
        migrations.DeleteModel(
            name='FirstPurchaseDiscount',
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
